name: Docker Image CI

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: cloudflare-partner-panel

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build . --file Dockerfile --tag "$IMAGE_NAME" --label "runnumber=${GITHUB_RUN_ID}"

      - name: Push image
        run: |
          IMAGE_ID="ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME"
          IMAGE_VERSION="${GITHUB_REF##*/v}"
          docker tag "$IMAGE_NAME" "$IMAGE_ID:$IMAGE_VERSION"
          docker tag "$IMAGE_NAME" "$IMAGE_ID:latest"
          docker push "$IMAGE_ID:$IMAGE_VERSION"
          docker push "$IMAGE_ID:latest"
